### PR TITLE
Go to top button bug fix

### PR DESCRIPTION
**Pull request by sshsrn**

### CODE REVIEW

**Comment by sshsrn** [comment]
https://user-images.githubusercontent.com/62781914/197387272-b30ec3d6-1103-435e-b139-db13a6790edc.mp4

Here is a screen recording for your reference.

**Comment by sshsrn** [comment]
fixes #51

**Comment by sshsrn** [comment]
@gn009 Kindly check!

**Comment by gn009** [comment]
> @gn009 Kindly check!

Kindly sync fork since your branch is lagging behind few commit @SSHSRN

**Comment by sshsrn** [comment]
done.

**Pull request merged**
